// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PTE_Test_Helper.Models;
using System;

namespace PTE_Test_Helper.Migrations
{
    [DbContext(typeof(PTE_Test_HelperContext))]
    partial class PTE_Test_HelperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PTE_Test_Helper.Models.Paragraph", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int>("Location");

                    b.Property<int>("ParentId");

                    b.HasKey("ID");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("PTE_Test_Helper.Models.RO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleId");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("ID");

                    b.ToTable("RO");
                });
#pragma warning restore 612, 618
        }
    }
}
